apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: netdebug
  name: netdebug
  namespace: netdebug
spec:  
  nodeSelector:
   "kubernetes.io/os": linux
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done;
    image: <your.registry>.azurecr.io/netdebug:v1
    name: netdebug
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
